### ISSUE TITLE
 Ciberseguridad

### ISSUE THREAD

**Issue by xNachooox2442** [OrganizacionProyecto/Aymara-App#11]
- Diseñar un plan de seguridad detallando las políticas a implementar basándose en buenas prácticas de seguridad, fundamentando ante qué vulnerabilidades y/o ataques se previene con cada política.

- Diseñar la autenticación con Auth0 o JWT fundamentando la elección.

- Publicar en la wiki los dos puntos anteriores.

**Comment by CeCogot** [comment]
Se confecciona Plan de seguridad de acuerdo a los requerimientos, objetivos, autenticacion,  autorizacion y politicas de contraseña.

**Comment by CeCogot** [comment]
De acuerdo  a los requerimientos se  agrega al documento como se implementa en el codigo el plan de seguridad diseñado para la App

**Comment by CeCogot** [comment]
La implementación JWT para la autenticación ha sido completada exitosamente. Ahora, los tokens se generan y verifican correctamente, asegurando que solo los usuarios autenticados puedan acceder a los recursos protegidos. Además, se han añadido medidas de seguridad adicionales, como la expiración de tokens , para prevenir el uso indebido y mejorar la protección contra ataques.
