### ISSUE TITLE
 Testeador de Software

### ISSUE THREAD

**Issue by xNachooox2442** [OrganizacionProyecto/Aymara-App#15]
- [x] Planificar 2 casos de prueba por cada integrante, para la app a desarrollar en el proyecto, de acuerdo a la plantilla de test Case propuesta en el Bloque, teniendo en cuenta los criterios de aceptación de las Historias de Usuarios. Dejar registro dentro de una nueva página de la WIKI, denominada testing.

**Comment by Nico2384** [comment]
Se testeo la app y se logro identificar errores de accesibilidad que fueron corregidos por ejemplo, no cumplía con las normas de relación entre los colores de fondo y principales, que ya fue solucionados,  se testeo el jwt arrojando como resultado el buen funcionamiento del mismo, entre otros test de cada componente y view de la app
