### ISSUE TITLE
 Ciberseguridad

### ISSUE THREAD

**Issue by xNachooox2442** [OrganizacionProyecto/Aymara-App#16]
- [x] Diseñar un plan de seguridad detallando las políticas a implementar basándose en buenas prácticas de seguridad, fundamentando ante qué vulnerabilidades y/o ataques se previene con cada política.
- [x] Diseñar la autenticación con Auth0 o JWT fundamentando la elección.
- [x] Publicar en la wiki los dos puntos anteriores.

**Comment by CeCogot** [comment]
La implementación de JSON Web Tokens (JWT) para la autenticación ha sido completada exitosamente. Ahora, los tokens se generan y verifican correctamente, asegurando que solo los usuarios autenticados puedan acceder a los recursos protegidos. Además, se han añadido medidas de seguridad adicionales, como la expiración de tokens  para prevenir el uso indebido y mejorar la protección contra ataques.
